"""empty message

Revision ID: 26bf0dc8012e
Revises: ce3649e06010
Create Date: 2018-05-26 14:31:38.135855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26bf0dc8012e'
down_revision = 'ce3649e06010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('move',
    sa.Column('postid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('content_title', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('publish_time', sa.DateTime(), nullable=True),
    sa.Column('like_num', sa.Integer(), nullable=True),
    sa.Column('share_num', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('postid')
    )
    op.create_index(op.f('ix_move_duration'), 'move', ['duration'], unique=False)
    op.create_index(op.f('ix_move_like_num'), 'move', ['like_num'], unique=False)
    op.create_index(op.f('ix_move_share_num'), 'move', ['share_num'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_move_share_num'), table_name='move')
    op.drop_index(op.f('ix_move_like_num'), table_name='move')
    op.drop_index(op.f('ix_move_duration'), table_name='move')
    op.drop_table('move')
    # ### end Alembic commands ###
